insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('LINK_PRE_RESERVA','Link pré-reserva','http://www.aluguerelaxe.com.br/arweb/prereserva.svlt?token=${token}&action=${action}');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('TELEFONES_CENTRAL_RESERVA','Telefones da Central de Reserva','(37)8412-7817 / (41)9667-5276 / (11)96290-0040 / (24)9275-3073');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PATH_CONTRATO_LOCATARIO','Path completo do contrato com locatário','/home/aluguerelaxe/www/contratos/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('LINK_CONTRATO_LOCATARIO','Url do contrato com locatário','http://www.aluguerelaxe.com.br/contratos/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PERC_COMISSAO_PADRAO_TEMPORADA','Percentual de Comissão Padrão Temporada','0.15');

INSERT INTO MENSAGEM VALUES ('MSG-0046', 'Não é permitido a digitação de e-mail dentro do campo ${1}.');
INSERT INTO MENSAGEM VALUES ('MSG-0047', 'Não é permitido a digitação de url dentro do campo ${1}.');
INSERT INTO MENSAGEM VALUES ('MSG-0048', 'Não é permitido a digitação de telefone dentro do campo ${1}.');
INSERT INTO MENSAGEM VALUES ('MSG-0049', 'Pré-reserva de imóvel de temporada realizada com sucesso.');
INSERT INTO MENSAGEM VALUES ('MSG-0050', 'Pré-reserva indicada já foi validada anteriormente');
INSERT INTO MENSAGEM VALUES ('MSG-0051', 'Validação da Pré-reserva realizada com sucesso');
INSERT INTO MENSAGEM VALUES ('MSG-0052', 'Informações de pagamento do token ${1} já foram validadas. Token Inválido.');
INSERT INTO MENSAGEM VALUES ('MSG-0053', 'Confirmação de pagamento realizada com sucesso');
INSERT INTO MENSAGEM VALUES ('MSG-0054', 'Pré-reserva ${1} cancelada com sucesso');
INSERT INTO MENSAGEM VALUES ('MSG-0055', 'Reserva ${1} foi cancelada em ${2}');
INSERT INTO MENSAGEM VALUES ('MSG-0056', 'Pagamento da reserva foi confirmada em ${1}');
INSERT INTO MENSAGEM VALUES ('MSG-0057', 'A pré-reserva ${1} ainda não foi confirmada. O Comando não foi executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0058', 'A identificação do solicitante #${1} é inválida. O Comando não foi executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0059', 'As informações de Banco, Agência e Conta Corrente do solicitante #${1} está imcompleta. Por favor, verifique seu cadastro.');
INSERT INTO MENSAGEM VALUES ('MSG-0060', 'A liberação de pagamento para o voucher #${1} já foi solicitada em ${2}.');
INSERT INTO MENSAGEM VALUES ('MSG-0061', 'A liberação de pagamento foi processada com sucesso. Em até 24 horas o AlugueRelaxe estará providenciando a transferência do depósito em conta corrente.');
INSERT INTO MENSAGEM VALUES ('MSG-0062', 'Voucher inválido. O comando não foi executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0063', 'Código de tracking inválido. O comando não foi executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0064', 'O pagamento da reserva não foi confirmado até o momento. O comando não foi executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0065', 'O pedido de liberação de pagamento só está autorizado a partir do dia ${1}.');
INSERT INTO MENSAGEM VALUES ('MSG-0066', 'A fase de pré-reserva não está concluída.');
INSERT INTO MENSAGEM VALUES ('MSG-0067', 'A fase de aprovação não está concluída.');
INSERT INTO MENSAGEM VALUES ('MSG-0068', 'A fase de confirmação do depósito não está concluída.');
INSERT INTO MENSAGEM VALUES ('MSG-0069', 'A fase de Liberação do depósito não está concluída.');
INSERT INTO MENSAGEM VALUES ('MSG-0070', 'A fase de transferência do depósito não está concluída.');
INSERT INTO MENSAGEM VALUES ('MSG-0071', 'Transferência de depósito Tracker# ${1} realizado com sucesso.');
INSERT INTO MENSAGEM VALUES ('MSG-0072', 'A Transferência de depósito Tracker# ${1} já foi realizada em ${2}. Comando não executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0073', 'Erro no preenchimento do formulário de reserva. Comando não executado.');
INSERT INTO MENSAGEM VALUES ('MSG-0074', 'Para a forma de pagamento ${2} era esperado valor previsto de depósito R$ ${1}.');
INSERT INTO MENSAGEM VALUES ('MSG-0075', 'Campo de valor está com valor negativo ${1}. Verifique.');
commit work;
