drop index UN_IMPL_CD_IMOVEL_PLANO;
CREATE INDEX UN_IMPL_CD_IMOVEL_PLANO
        ON IMOVEL_PLANO(IMOV_CD_IMOVEL,PLAN_CD_PLANO);
		
ALTER TABLE PLANO ADD PLAN_QT_MAX_FOTO_PERMITIDOS  NUMERIC(2) DEFAULT 3;

ALTER TABLE IMOVEL_IMAGEM_VIDEO ADD IMIV_TX_HASH   VARCHAR(40);

CREATE GENERATOR SEQ_IMIV_TX_HASH;
SET    GENERATOR SEQ_IMIV_TX_HASH  TO 1;

UPDATE IMOVEL_IMAGEM_VIDEO SET IMIV_TX_HASH = GEN_ID("SEQ_IMIV_TX_HASH", 1);
commit work;

CREATE UNIQUE INDEX UN_IMIV_TX_HASH
ON IMOVEL_IMAGEM_VIDEO (IMOV_CD_IMOVEL, IMIV_TX_HASH);

UPDATE PLANO SET PLAN_QT_MAX_FOTO_PERMITIDOS = 3;
commit work;

drop sequence SEQ_IMIV_TX_HASH;



