insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('URL_THREADS','URL para acompanhamento das dúvidas entre visitante e anunciante','http://www.aluguerelaxe.com.br/arweb/JXControllerSmartInterface?cmd=dtgThread&hash=${HASH}&omc=${OMC}');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('URL_THREADS_APROVAR','URL para aprovar uma trhead sem edição','http://www.aluguerelaxe.com.br/arweb/aprovarthread.svlt?hid=${hash}&action=${action}&modo=${modo}');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('URL_THREADS_APROVAR_EDITADO','URL para aprovar uma trhead editada pelo moderador','http://www.aluguerelaxe.com.br/arweb/aprovarthread.svlt?hid=${hash}&action=${action}&modo=${modo}');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PATH_GALERIA_FOTOS_THREAD','Path das fotos dos visitantes das threads','/home/aluguerelaxe/www/stream/thread/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('URL_GALERIA_PERFIL_ANUNCIANTES','Path das fotos dos anunciantes','/stream/fotos/${clienteid}/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('URL_BASE_IMAGENS','URL base das imagens das fotos dos anunciantes','images/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PATH_GALERIA_FOTOS_PERFIL','Path para galeria de fotos do perfil do anunciante','/home/aluguerelaxe/www/stream/fotos/${clienteid}/');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('FOTO_NO_FACE','Nome da imagem padrão perfil sem foto','noface.png');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('SMS_TAMANHO_MAXIMO','Tamanho maximo (bytes) das mensagens via SMS','140');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PNEG_ANUNCIANTE_SEM_FOTO_PERFIL','Pontuação negativa para anunciante sem foto no perfil','100');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PNEG_ANUNCIANTE_NAO_VERIFICADO','Pontuação negativa para anunciante sem verificação','100');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('PNEG_TAXA_RESPOSTA_BAIXA','Pontuação negativa para baixo índice de respostas as perguntas','100');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('TAXA_RESPOSTA_MINIMA','Taxa de resposta mínima aceitável para anunciante','0.75');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('CHAVE_GERAL_GERENCIADOR_ALERTA_24H','Chave geral para processo do Gerenciador de Alerta 24h.','ON');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('LINK_ACOMPANHAMENTO_WORKFLOW_PRE_RESERVA','Link para acompanhamento da reserva no portal','http://www.aluguerelaxe.com.br/arweb/JXControllerSmartInterface?cmd=dtgReservas&hash=${hash}&omc=${omc}');
insert into VARIAVEL (VARI_CD_VARIAVEL,VARI_TX_DESCRICAO,VARI_TX_VALOR_CONTEUDO) VALUES ('LINK_AVALIACAO_RESERVA','Link para avalição da reserva no portal','http://www.aluguerelaxe.com.br/arweb/JXControllerSmartInterface?cmd=dtgAvaliarImovel&hash=${hash}&omc=${omc}');
commit work;

INSERT INTO MENSAGEM VALUES ('MSG-0098', 'Olá, o visitante ${1} precisa que você responda as dúvidas sobre seu imóvel localizado ${2} - ${3} ::Título:: ${4}');
INSERT INTO MENSAGEM VALUES ('MSG-0099', 'DÚVIDA SOBRE SEU IMOVEL EM ${2} - ${3}');
INSERT INTO MENSAGEM VALUES ('MSG-0100', '${1} tem duvidas sobre seu imovel localizado ${2} - ${3}. Verifique seu email ${5}. :-D #AlugueRelaxe');
INSERT INTO MENSAGEM VALUES ('MSG-0101', 'Thread ${1} aguardando moderacao e aprovacao de liberacao. :-D #AlugueRelaxe');
INSERT INTO MENSAGEM VALUES ('MSG-0102', 'É necessário colocar pelo menos um telefone de contato.');
INSERT INTO MENSAGEM VALUES ('MSG-0103', 'É necessário preencher o valor de pelo menos uma diária.');
INSERT INTO MENSAGEM VALUES ('MSG-0104', 'Sua duvida imovel em ${1}-${2} foi respondida. Leia em ${3}.');
INSERT INTO MENSAGEM VALUES ('MSG-0105', 'Sua solicitação foi enviada com sucesso. Aproveite para colocar o email aluguerelaxe@aluguerelaxe.com.br na lista de remetentes confiáveis.');
INSERT INTO MENSAGEM VALUES ('MSG-0106', 'MSG FALE CONOSCO: recebida de ${1} assunto: ${2}. Verifique seu email aluguerelaxe@aluguerelaxe.com.br');
INSERT INTO MENSAGEM VALUES ('MSG-0107', 'Sua resposta foi enviada com sucesso. Está aguardando a aprovação do moderador para ser publicada.');
INSERT INTO MENSAGEM VALUES ('MSG-0108', 'Sua dúvida foi enviada com sucesso. Está aguardando a aprovação do moderador para ser publicada.');
INSERT INTO MENSAGEM VALUES ('MSG-0109', 'Pré-Reserva ${1} para ${2} em ${3}-${4} aguarda sua aprovacao URGENTE.');
INSERT INTO MENSAGEM VALUES ('MSG-0110', 'Data de Checkin não pode ser inferior a data de hoje.');
INSERT INTO MENSAGEM VALUES ('MSG-0111', 'Data de Checkout não pode ser anterior a data de Checkin.');
INSERT INTO MENSAGEM VALUES ('MSG-0112', 'A data prevista de depósito deve ser entre hoje e anterior a data de Checkin.');
INSERT INTO MENSAGEM VALUES ('MSG-0113', 'Esta negociação está somente disponível para leitura e não pode ser modificada.');
INSERT INTO MENSAGEM VALUES ('MSG-0114', 'Código de contato com anunciante inválido.');
INSERT INTO MENSAGEM VALUES ('MSG-0115', 'Gestor, um comentario sobre imovel alugado foi emitido e aguarda sua aprovacao. Verifique e-mail.');
INSERT INTO MENSAGEM VALUES ('MSG-0116', 'Avaliação do imóvel e anfitrião realizadas com sucesso e entrarão em fluxo de aprovação com o moderador. Obrigado por emitir seu testemunho.');
INSERT INTO MENSAGEM VALUES ('MSG-0117', 'AlugueRelaxe:Liberacao do voucher ${1} reserva ${2} de RS ${3} foi aprovado e sera transferida em ate 24 horas para sua conta corrente.');
INSERT INTO MENSAGEM VALUES ('MSG-0118', 'AlugueRelaxe:Reserva confirmada para seu imovel ${1}/${2}.Pagamento de RS ${3} realizado ao AlugueRelaxe. Link do contrato de locacao em seu e-mail ${4}.');
INSERT INTO MENSAGEM VALUES ('MSG-0119', 'AlugueRelaxe:Pre-Reserva confirmada para seu imovel ${1}/${2}.Aguardando pagamento de RS ${3} ao AlugueRelaxe. +Detalhes e-mail ${4}.');
INSERT INTO MENSAGEM VALUES ('MSG-0120', 'É preciso fazer uma avaliação do imóvel. Marque uma das estrelas. 1 = Péssimo; 5 = Excelente');
INSERT INTO MENSAGEM VALUES ('MSG-0121', 'É preciso fazer uma avaliação do anfitrião. Marque uma das estrelas. 1 = Péssimo; 5 = Excelente');
INSERT INTO MENSAGEM VALUES ('MSG-0122', 'AlugueRelaxe: ${1} postou um comentario e uma avaliacao sobre a temporada no seu imovel em ${2}-${3}.');
INSERT INTO MENSAGEM VALUES ('MSG-0123', 'Avaliação para reserva já foi emitida.');
commit work;
