ALTER TABLE IMOVEL
ADD IMOV_SQ_OFERECIMENTO INTEGER
DEFAULT 0 
NOT NULL ;

UPDATE IMOVEL
SET IMOV_SQ_OFERECIMENTO = 0;

CREATE INDEX IX_IMOV_SQ_OFERECIMENTO 
ON IMOVEL(IMOV_SQ_OFERECIMENTO);

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_IN_ALERTA24H VARCHAR(1)
DEFAULT 'S' 
NOT NULL 
CHECK (IMCA_IN_ALERTA24H in ('S','N')) ;

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_IN_ALERTA24H = 'N';

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_IN_QUEUED_24H VARCHAR(1)
DEFAULT 'N' 
NOT NULL 
CHECK (IMCA_IN_QUEUED_24H IN ('S','N')) ;

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_IN_QUEUED_24H = 'N';

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_DT_QUEUED TIMESTAMP;

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_SQ_OFERECIMENTO INTEGER
DEFAULT 0 
NOT NULL ;

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_SQ_OFERECIMENTO = 0;

CREATE INDEX IX_IMCA_SQ_OFERECIMENTO ON IMOVEL_CONTATO_ANUNCIANTE(IMCA_SQ_OFERECIMENTO);

DROP TABLE FILA_SMS;

CREATE TABLE FILA_SMS
(
    FISM_ID INTEGER NOT NULL,
    FISM_TX_CELULAR VARCHAR(11) NOT NULL,
    FISM_TX_MSG VARCHAR(140) NOT NULL,
    FISM_IN_QUEUED VARCHAR(1) DEFAULT 'N' CHECK(FISM_IN_QUEUED IN ('S','N'))  NOT NULL,
    FISM_DT_QUEUED TIMESTAMP,
    FISM_IN_MODO VARCHAR(1) DEFAULT 'M' CHECK(FISM_IN_MODO IN ('M','G'))  NOT NULL,
    FISM_DT_ENVIO_GATEWAY TIMESTAMP,
    FISM_DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    CONSTRAINT PK_FISM_ID
        PRIMARY KEY(FISM_ID)
);


/******************************************************************/
/* TABELA TIPO DE ALERTA                                          */
/******************************************************************/
CREATE TABLE TIPO_ALERTA24H
(
    TIAL_ID INTEGER NOT NULL,
    TIAL_NM_TIPO_ALERTA VARCHAR(50) NOT NULL,
    TIAL_NM_WORKER VARCHAR(500) NOT NULL,
    TIAL_IN_STATUS VARCHAR(1) DEFAULT 'A' CHECK(TIAL_IN_STATUS IN ('A','I'))  NOT NULL,
    TIAL_DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    CONSTRAINT PK_TIAL_ID
        PRIMARY KEY(TIAL_ID)

);

CREATE TABLE FILA_ALERTA24H
(
    FIAL_ID INTEGER NOT NULL,
    TIAL_ID INTEGER NOT NULL,
    IMOV_CD_IMOVEL INTEGER NOT NULL,
    IMCA_CD_IMOVEL_CONTATO_ANU VARCHAR(40) NOT NULL,
    FIAL_IN_EMITIDO VARCHAR(1) DEFAULT 'N' CHECK(FIAL_IN_EMITIDO IN ('S','N'))  NOT NULL,
    FIAL_DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    CONSTRAINT PK_FIAL_ID
        PRIMARY KEY(FIAL_ID)
);



ALTER TABLE FILA_ALERTA24H
    ADD CONSTRAINT FK_ALER_TIAL
        FOREIGN KEY (TIAL_ID) 
            REFERENCES TIPO_ALERTA24H(TIAL_ID) ON DELETE CASCADE;

ALTER TABLE FILA_ALERTA24H
    ADD CONSTRAINT FK_ALER_IMCA
        FOREIGN KEY (IMCA_CD_IMOVEL_CONTATO_ANU) 
            REFERENCES IMOVEL_CONTATO_ANUNCIANTE(IMCA_CD_IMOVEL_CONTATO_ANU) ON DELETE CASCADE;

ALTER TABLE FILA_ALERTA24H
    ADD CONSTRAINT FK_ALER_CLIE
        FOREIGN KEY (IMOV_CD_IMOVEL) 
            REFERENCES IMOVEL(IMOV_CD_IMOVEL) ON DELETE CASCADE;

            
SET    GENERATOR SEQ_CHAT_CD_CHAT  TO 10000;

DROP GENERATOR SEQ_FISM_ID;
CREATE GENERATOR SEQ_FISM_ID;
SET GENERATOR SEQ_FISM_ID TO 1000;

CREATE GENERATOR SEQ_TIAL_ID;
SET GENERATOR SEQ_TIAL_ID TO 1000;

CREATE GENERATOR SEQ_ALER_ID;
SET GENERATOR SEQ_ALER_ID TO 1;

CREATE GENERATOR SEQ_OFERECIMENTO;
SET GENERATOR SEQ_OFERECIMENTO TO 5000;

update imovel set imov_sq_oferecimento = (SELECT GEN_ID( "SEQ_OFERECIMENTO", 1 ) FROM RDB$DATABASE);
update imovel_contato_Anunciante set imca_sq_oferecimento = (SELECT GEN_ID( "SEQ_OFERECIMENTO", 1 ) FROM RDB$DATABASE);
commit work;



