

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_IN_ALERTA24H VARCHAR(1)
DEFAULT 'S' 
NOT NULL 
CHECK (IMCA_IN_ALERTA24H IN ('S','N'));

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_IN_ALERTA24H = 'S';

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_IN_QUEUED_24H VARCHAR(1)
DEFAULT 'N' 
NOT NULL 
CHECK (IMCA_IN_QUEUED_24H IN ('S','N')) ;

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_IN_QUEUED_24H = 'N';

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_DT_QUEUED TIMESTAMP;

