ALTER TABLE RESERVA DROP RESE_IN_AVALIACAO;
ALTER TABLE RESERVA DROP RESE_TX_AVALIACAO;

DROP INDEX UN_LOTE_TX_EMAIL;

ALTER TABLE CLIENTE ADD CLIE_NU_PERG INTEGER DEFAULT 0 NOT NULL     ;
UPDATE CLIENTE SET CLIE_NU_PERG = 0;

ALTER TABLE CLIENTE ADD CLIE_NU_RESP INTEGER DEFAULT 0 NOT NULL     ;
UPDATE CLIENTE SET CLIE_NU_RESP = 0;

ALTER TABLE CLIENTE ADD CLIE_TX_FOTO_PERFIL VARCHAR(50) ;
ALTER TABLE CLIENTE ADD CLIE_TX_FOTO_CHAT VARCHAR(50) ;
    
ALTER TABLE CLIENTE
ADD CLIE_IN_VERIFICADO VARCHAR(1)
DEFAULT 'N' 
NOT NULL 
CHECK (CLIE_IN_VERIFICADO IN ('S','N')) ;

UPDATE CLIENTE
SET CLIE_IN_VERIFICADO = 'N';

ALTER TABLE IMOVEL
ADD IMOV_IN_OBJETIVO VARCHAR(1)
DEFAULT 'T' 
NOT NULL 
CHECK (IMOV_IN_OBJETIVO IN ('A','T','V')) ;

UPDATE IMOVEL
SET IMOV_IN_OBJETIVO = 'T';
                        
ALTER TABLE IMOVEL
ADD IMOV_VL_TARIFA_BASICA INTEGER
DEFAULT 0 ;


update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'TAPR_TX_PERIODO') and
(RDB$RELATION_NAME = 'TABELA_PRECO');

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'TAPR_DT_INICIO') and
(RDB$RELATION_NAME = 'TABELA_PRECO')
;

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'TAPR_DT_DATA_FIM') and
(RDB$RELATION_NAME = 'TABELA_PRECO')
;

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_TX_IMG_VISITANTE VARCHAR(50);
    
ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_CD_OMC_ANUNCIANTE VARCHAR(12);

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_CD_OMC_VISITANTE VARCHAR(12);

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_CD_OMC_ADMIN VARCHAR(12);

ALTER TABLE IMOVEL_CONTATO_ANUNCIANTE
ADD IMCA_IN_THREAD_STATUS VARCHAR(1)
DEFAULT 'I' 
NOT NULL 
CHECK (IMCA_IN_THREAD_STATUS IN ('A','I')) ;

UPDATE IMOVEL_CONTATO_ANUNCIANTE
SET IMCA_IN_THREAD_STATUS = 'I';
    

/************************************************************************/
/* IMOVEL_CONTATO_THREAD                                                */
/************************************************************************/
/* Valores para IMCT_IN_STATUS                                          */
/* A = Ativo                                                            */
/* P = Pendente - Aguardando aprovacao do administrador(moderador)      */
/************************************************************************/
/* Valores para IMCT_IN_ORIGEM                                          */
/* A = Mensagem foi redigida pelo anunciante                            */
/* V = Mensagem foi redigida pelo visitante                             */
/* M = Mensagem foi redigida pelo Administrador                         */
/************************************************************************/
/* Valores para IMCT_IN_MODO                                            */
/* PR = Pergunta ou Resposta                                            */
/* CO = Comentários                                                     */
/************************************************************************/
CREATE TABLE IMOVEL_CONTATO_THREAD
(
    IMCT_ID INTEGER  NOT NULL ,
    IMCT_ID_PARENT INTEGER,
    IMCA_CD_IMOVEL_CONTATO_ANU VARCHAR(40) NOT NULL,
    IMCT_IN_ORIGEM VARCHAR(1) DEFAULT 'V' CHECK(IMCT_IN_ORIGEM IN ('V','A','M'))  NOT NULL,
    IMCT_IN_STATUS VARCHAR(1) DEFAULT 'P' CHECK(IMCT_IN_STATUS IN ('P','A'))  NOT NULL,
    IMCT_IN_MODO VARCHAR(2) DEFAULT 'PR' CHECK(IMCT_IN_MODO IN ('PR','CO'))  NOT NULL,
    IMCT_DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IMCT_TX_HASH   VARCHAR(40)  NOT NULL,
    IMCT_TX_THREAD VARCHAR(2000) NOT NULL,
    IMCT_TX_THREAD_EDITADA VARCHAR(2000) NOT NULL,
    CONSTRAINT PK_IMCT_ID  
        PRIMARY KEY(IMCT_ID)
);

CREATE INDEX IX_IMCT_ID_IMOVEL_CONTATO_ANU ON IMOVEL_CONTATO_THREAD(IMCA_CD_IMOVEL_CONTATO_ANU);

CREATE UNIQUE INDEX UN_IMCT_TX_HASH ON IMOVEL_CONTATO_THREAD(IMCT_TX_HASH);


ALTER TABLE RESERVA
ADD RESE_VL_TAXA_SERVICO NUMERIC(10,2)
DEFAULT 0 
CHECK (RESE_VL_TAXA_SERVICO > -1) ;

    
ALTER TABLE RESERVA
ADD IMCA_CD_IMOVEL_CONTATO_ANU VARCHAR(40);

ALTER TABLE RESERVA
ADD RESE_TX_IMG_VISITANTE VARCHAR(50);

ALTER TABLE RESERVA
ADD RESE_NU_NOTA_IMOVEL INTEGER
DEFAULT 0 
CHECK (RESE_NU_NOTA_IMOVEL IN (0,1,2,3,4,5));

ALTER TABLE RESERVA
ADD RESE_NU_NOTA_ANFITRIAO INTEGER
DEFAULT 0 
CHECK (RESE_NU_NOTA_ANFITRIAO IN (0,1,2,3,4,5)) ;
    
CREATE INDEX IX_RESE_IMCA_CD_IMOV_CONT
    ON RESERVA(IMCA_CD_IMOVEL_CONTATO_ANU);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESE_IMCA_CD_IMOVEL_CONTATO 
        FOREIGN KEY (IMCA_CD_IMOVEL_CONTATO_ANU) 
            REFERENCES IMOVEL_CONTATO_ANUNCIANTE(IMCA_CD_IMOVEL_CONTATO_ANU);
            
ALTER TABLE IMOVEL_CONTATO_THREAD
    ADD CONSTRAINT FK_IMCT_IMCA
        FOREIGN KEY (IMCA_CD_IMOVEL_CONTATO_ANU) 
            REFERENCES IMOVEL_CONTATO_ANUNCIANTE(IMCA_CD_IMOVEL_CONTATO_ANU) ON DELETE CASCADE;


CREATE GENERATOR SEQ_IMCT_ID ;
SET    GENERATOR SEQ_IMCT_ID TO 1000;

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


























    
