package br.com.jcv.aluguerelaxe.client.componente.listbox;

public class PaisesListBox extends ComponenteListBox {
	public PaisesListBox(boolean b) {
		super(b);
		
		this.setWidth("200px");
		this.addItem("Brasil");
		this.addItem("Afeganist\u00e3o");
		this.addItem("\u00e1frica do Sul");
		this.addItem("Akrotiri");
		this.addItem("Alb\u00e2nia");
		this.addItem("Alemanha");
		this.addItem("Andorra");
		this.addItem("Angola");
		this.addItem("Anguila");
		this.addItem("Ant\u00e1rctida");
		this.addItem("Ant\u00edgua e Barbuda");
		this.addItem("Antilhas Neerlandesas");
		this.addItem("Ar\u00e1bia Saudita");
		this.addItem("Arctic Ocean");
		this.addItem("Arg\u00e9lia");
		this.addItem("Argentina");
		this.addItem("Arm\u00e9nia");
		this.addItem("Aruba");
		this.addItem("Ashmore and Cartier Islands");
		this.addItem("Atlantic Ocean");
		this.addItem("Austr\u00e1lia");
		this.addItem("\u00e1ustria");
		this.addItem("Azerbaij\u00e3o");
		this.addItem("Baamas");
		this.addItem("Bangladeche");
		this.addItem("Barbados");
		this.addItem("Bar\u00e9m");
		this.addItem("B\u00e9lgica");
		this.addItem("Belize");
		this.addItem("Benim");
		this.addItem("Bermudas");
		this.addItem("Bielorr\u00fassia");
		this.addItem("Birm\u00e2nia");
		this.addItem("Bol\u00edvia");
		this.addItem("B\u00f3snia e Herzegovina");
		this.addItem("Botsuana");
		this.addItem("Brasil");
		this.addItem("Brunei");
		this.addItem("Bulg\u00e1ria");
		this.addItem("Burquina Faso");
		this.addItem("Bur\u00fandi");
		this.addItem("But\u00e3o");
		this.addItem("Cabo Verde");
		this.addItem("Camar\u00f5es");
		this.addItem("Camboja");
		this.addItem("Canad\u00e1");
		this.addItem("Catar");
		this.addItem("Cazaquist\u00e3o");
		this.addItem("Chade");
		this.addItem("Chile");
		this.addItem("China");
		this.addItem("Chipre");
		this.addItem("Clipperton Island");
		this.addItem("Col\u00f4mbia");
		this.addItem("Comores");
		this.addItem("Congo-Brazzaville");
		this.addItem("Congo-Kinshasa");
		this.addItem("Coral Sea Islands");
		this.addItem("Coreia do Norte");
		this.addItem("Coreia do Sul");
		this.addItem("Costa do Marfim");
		this.addItem("Costa Rica");
		this.addItem("Cro\u00e1cia");
		this.addItem("Cuba");
		this.addItem("Dhekelia");
		this.addItem("Dinamarca");
		this.addItem("Dom\u00ednica");
		this.addItem("Egipto");
		this.addItem("Emiratos \u00e1rabes Unidos");
		this.addItem("Equador");
		this.addItem("Eritreia");
		this.addItem("Eslov\u00e1quia");
		this.addItem("Eslov\u00e9nia");
		this.addItem("Espanha");
		this.addItem("Estados Unidos");
		this.addItem("Est\u00f3nia");
		this.addItem("Eti\u00f3pia");
		this.addItem("Faro\u00e9");
		this.addItem("Fiji");
		this.addItem("Filipinas");
		this.addItem("Finl\u00e2ndia");
		this.addItem("Fran\u00e7a");
		this.addItem("Gab\u00e3o");
		this.addItem("G\u00e2mbia");
		this.addItem("Gana");
		this.addItem("Gaza Strip");
		this.addItem("Ge\u00f3rgia");
		this.addItem("Ge\u00f3rgia do Sul e Sandwich do Sul");
		this.addItem("Gibraltar");
		this.addItem("Granada");
		this.addItem("Gr\u00e9cia");
		this.addItem("Gronel\u00e2ndia");
		this.addItem("Guame");
		this.addItem("Guatemala");
		this.addItem("Guernsey");
		this.addItem("Guiana");
		this.addItem("Guin\u00e9");
		this.addItem("Guin\u00e9 Equatorial");
		this.addItem("Guin\u00e9-Bissau");
		this.addItem("Haiti");
		this.addItem("Honduras");
		this.addItem("Hong Kong");
		this.addItem("Hungria");
		this.addItem("I\u00e9men");
		this.addItem("Ilha Bouvet");
		this.addItem("Ilha do Natal");
		this.addItem("Ilha Norfolk");
		this.addItem("Ilhas Caim\u00e3o");
		this.addItem("Ilhas Cook");
		this.addItem("Ilhas dos Cocos");
		this.addItem("Ilhas Falkland");
		this.addItem("Ilhas Heard e McDonald");
		this.addItem("Ilhas Marshall");
		this.addItem("Ilhas Salom\u00e3o");
		this.addItem("Ilhas Turcas e Caicos");
		this.addItem("Ilhas Virgens Americanas");
		this.addItem("Ilhas Virgens Brit\u00e2nicas");
		this.addItem("\u00edndia");
		this.addItem("Indian Ocean");
		this.addItem("Indon\u00e9sia");
		this.addItem("Ir\u00e3o");
		this.addItem("Iraque");
		this.addItem("Irlanda");
		this.addItem("Isl\u00e2ndia");
		this.addItem("Israel");
		this.addItem("It\u00e1lia");
		this.addItem("Jamaica");
		this.addItem("Jan Mayen");
		this.addItem("Jap\u00e3o");
		this.addItem("Jersey");
		this.addItem("Jibuti");
		this.addItem("Jord\u00e2nia");
		this.addItem("Kuwait");
		this.addItem("Laos");
		this.addItem("Lesoto");
		this.addItem("Let\u00f3nia");
		this.addItem("L\u00edbano");
		this.addItem("Lib\u00e9ria");
		this.addItem("L\u00edbia");
		this.addItem("Listenstaine");
		this.addItem("Litu\u00e2nia");
		this.addItem("Luxemburgo");
		this.addItem("Macau");
		this.addItem("Maced\u00f3nia");
		this.addItem("Madag\u00e1scar");
		this.addItem("Mal\u00e1sia");
		this.addItem("Mal\u00e1vi");
		this.addItem("Maldivas");
		this.addItem("Mali");
		this.addItem("Malta");
		this.addItem("Man, Isle of");
		this.addItem("Marianas do Norte");
		this.addItem("Marrocos");
		this.addItem("Maur\u00edcia");
		this.addItem("Maurit\u00e2nia");
		this.addItem("Mayotte");
		this.addItem("M\u00e9xico");
		this.addItem("Micron\u00e9sia");
		this.addItem("Mo\u00e7ambique");
		this.addItem("Mold\u00e1via");
		this.addItem("M\u00f3naco");
		this.addItem("Mong\u00f3lia");
		this.addItem("Monserrate");
		this.addItem("Montenegro");
		this.addItem("Mundo");
		this.addItem("Nam\u00edbia");
		this.addItem("Nauru");
		this.addItem("Navassa Island");
		this.addItem("Nepal");
		this.addItem("Nicar\u00e1gua");
		this.addItem("N\u00edger");
		this.addItem("Nig\u00e9ria");
		this.addItem("Niue");
		this.addItem("Noruega");
		this.addItem("Nova Caled\u00f3nia");
		this.addItem("Nova Zel\u00e2ndia");
		this.addItem("Om\u00e3");
		this.addItem("Pacific Ocean");
		this.addItem("Pa\u00edses Baixos");
		this.addItem("Palau");
		this.addItem("Panam\u00e1");
		this.addItem("Papua-Nova Guin\u00e9");
		this.addItem("Paquist\u00e3o");
		this.addItem("Paracel Islands");
		this.addItem("Paraguai");
		this.addItem("Peru");
		this.addItem("Pitcairn");
		this.addItem("Polin\u00e9sia Francesa");
		this.addItem("Pol\u00f3nia");
		this.addItem("Porto Rico");
		this.addItem("Portugal");
		this.addItem("Qu\u00e9nia");
		this.addItem("Quirguizist\u00e3o");
		this.addItem("Quirib\u00e1ti");
		this.addItem("Reino Unido");
		this.addItem("Rep\u00fablica Centro-Africana");
		this.addItem("Rep\u00fablica Checa");
		this.addItem("Rep\u00fablica Dominicana");
		this.addItem("Rom\u00e9nia");
		this.addItem("Ruanda");
		this.addItem("R\u00fassia");
		this.addItem("Salvador");
		this.addItem("Samoa");
		this.addItem("Samoa Americana");
		this.addItem("Santa Helena");
		this.addItem("Santa L\u00facia");
		this.addItem("S\u00e3o Crist\u00f3v\u00e3o e Neves");
		this.addItem("S\u00e3o Marinho");
		this.addItem("S\u00e3o Pedro e Miquelon");
		this.addItem("S\u00e3o Tom\u00e9 e Pr\u00edncipe");
		this.addItem("S\u00e3o Vicente e Granadinas");
		this.addItem("Sara Ocidental");
		this.addItem("Seicheles");
		this.addItem("Senegal");
		this.addItem("Serra Leoa");
		this.addItem("S\u00e9rvia");
		this.addItem("Singapura");
		this.addItem("S\u00edria");
		this.addItem("Som\u00e1lia");
		this.addItem("Southern Ocean");
		this.addItem("Spratly Islands");
		this.addItem("Sri Lanca");
		this.addItem("Suazil\u00e2ndia");
		this.addItem("Sud\u00e3o");
		this.addItem("Su\u00e9cia");
		this.addItem("Su\u00ed\u00e7a");
		this.addItem("Suriname");
		this.addItem("Svalbard e Jan Mayen");
		this.addItem("Tail\u00e2ndia");
		this.addItem("Taiwan");
		this.addItem("Tajiquist\u00e3o");
		this.addItem("Tanz\u00e2nia");
		this.addItem("Territ\u00f3rio Brit\u00e2nico do Oceano \u00edndico");
		this.addItem("Territ\u00f3rios Austrais Franceses");
		this.addItem("Timor Leste");
		this.addItem("Togo");
		this.addItem("Tokelau");
		this.addItem("Tonga");
		this.addItem("Trindade e Tobago");
		this.addItem("Tun\u00edsia");
		this.addItem("Turquemenist\u00e3o");
		this.addItem("Turquia");
		this.addItem("Tuvalu");
		this.addItem("Ucr\u00e2nia");
		this.addItem("Uganda");
		this.addItem("Uni\u00e3o Europeia");
		this.addItem("Uruguai");
		this.addItem("Usbequist\u00e3o");
		this.addItem("Vanuatu");
		this.addItem("Vaticano");
		this.addItem("Venezuela");
		this.addItem("Vietname");
		this.addItem("Wake Island");
		this.addItem("Wallis e Futuna");
		this.addItem("West Bank");
		this.addItem("Z\u00e2mbia");
		this.addItem("Zimbabu\u00e9");
	}

}
